### PR TITLE
Move plugin towards 0.5

### PR DESCRIPTION
**Pull request by foopoiuyt**
I took the base changes made to the 0.4 branch for moving the build to 0.5, but this doesn't have an updated sig.

### CODE REVIEW

**Comment by foopoiuyt** [comment]
@tboerger Moved what was in types.go into plugin.go

**Comment by tboerger** [comment]
Just some nitpick, otherwise it looks pretty well.

Missing parts like Dockerfile for arm can be added in a followup

**Comment by tboerger** [comment]
LGTM

**Comment by Bugagazavr** [comment]
LGTM

**Pull request merged**
