### PR TITLE
Expand usage, not only for drone and github

### PR DESCRIPTION
**Pull request by mapleeit**
This plugin could be expanded. Now it's only custom-made for drone and github.com. We can change that without breaking its original functions.

### CODE REVIEW

**Comment by mapleeit** [comment]
All right, didn't realize that before. I modified README again.

**Comment by mapleeit** [comment]
@tboerger PTAL. Sorry for the force-push. : (

**Comment by mapleeit** [comment]
ping @tboerger

**Comment by mapleeit** [comment]
@tboerger Sorry to disturb. Could this been merged and released?

**Comment by tboerger** [comment]
I want to get an opinion from other maintainers first.

**Comment by mapleeit** [comment]
@tboerger Sure, got it.
@xoxys Thanks for your review.

BTW. #25 can be closed because this already fix/satisfy it.

**Pull request merged**
